<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zaloguj si i korzystaj z nowoczesnego_5852bd</name>
   <tag></tag>
   <elementGuidId>51c21639-95bd-44b9-b79b-9525d5917e1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='password'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-login-password-field.password-field-active.ng-pristine.ng-untouched.ng-valid.ng-not-empty.ng-valid-maxlength.ng-dirty-add.ng-valid-parse-add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-login-password-field password-field-active ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-maxlength ng-dirty-add ng-valid-parse-add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-password-field-number</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>passwordFieldActive.inputSelectedCb({msg: $event})</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>passwordFieldActive.model[passwordFieldActive.number]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-paste</name>
      <type>Main</type>
      <value>passwordFieldActive.onPaste($event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;os-windows browser-chrome device-unknown&quot;]/ui-view[1]/div[@class=&quot;_3yz0RkzgWF4XqYW6f_pIvH auth-page-footer&quot;]/div[@class=&quot;slide-container&quot;]/div[@class=&quot;slide&quot;]/div[@class=&quot;_2ucq4_5Pa9Kai1R10BGiiN&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/form[@class=&quot;ng-pristine ng-valid ng-valid-maxlength ng-dirty-add ng-valid-parse-add ng-animate ng-pristine-remove&quot;]/div[@class=&quot;middle-part page-part col-lg-10 col-lg-push-1 col-sm-12&quot;]/div[@class=&quot;_3xpCySe-qm6fhwm2uluWfS&quot;]/div[@class=&quot;password-fields-wrapper&quot;]/div[@class=&quot;mobile-pass&quot;]/passwordfieldactive[1]/div[@class=&quot;btn _4EU3YUrqokGMYms3Meq5j password-field-button active&quot;]/div[@class=&quot;password-field-content&quot;]/input[@class=&quot;input-login-password-field password-field-active ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-maxlength ng-dirty-add ng-valid-parse-add&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='password'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/passwordfieldactive/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
